### ISSUE TITLE
Path contains double backslashes in the Windows log window

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#1014]
**Describe the bug**
When trying to open an unsupported file, the path contains double backslashes.

**To Reproduce**
 1. Open a unsupported file
 2. Look at the log window

![image](https://github.com/f3d-app/f3d/assets/6069752/b97ebcd4-3727-464c-a6f8-430ab57c5ddd)

**Expected behavior**
Single backslash

**System Information:**
 - OS: Windows

**F3D Information**
2.2 RC2

**Comment by snoyer** [comment]
using `generic_string()` solves the issue in so far as the output does not contain double back slashes (`\\`) anymore but the separators have been converted to forward slashes ('/') which can be used on Windows but are not preferred.

@shambhupatil can you check if using `filePath.string()` instead of `filePath.generic_string()` produces single backslashes?

**Comment by shambhupatil** [comment]
Yes, path.string() does produce single backslash.

**Comment by mwestphal** [comment]
That sounds like the right fix!

**Comment by snoyer** [comment]
> Yes, path.string() does produce single backslash.

@shambhupatil nice! next step is the PR then :)
