### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by spiraloid** [f3d-app/f3d#1059]
**Is your feature request related to a problem? Please describe.**
I wish the autoplay started automatically when reviewing files.

**Describe the solution you'd like**
it should have the option to automatically play animation on start like a movie player.

**Describe alternatives you've considered**
sketchfab

**Additional context**
see fun.
https://skfb.ly/6QStY

**Contribution**
Please tell us if you are able to contribute (Can you develop this new feature?)
Don't worry, you can still post a feature request if you cannot contribute!*

**Comment by mwestphal** [comment]
That should be a trivial option to add, wdyt @Meakk ?

**Comment by Meakk** [comment]
Yes, looks straightforward and useful

**Comment by technologeli** [comment]
Hello, I'd like to work on this issue. This is my first time exploring open-source, so if there is anything I can do to improve please let me know.

After looking through the codebase, it seems like an autoplay option should be accessible through a CLI flag and in the configuration JSON file, perhaps something like `--autoplay`. It should also be able to be toggled while running the application - something like `S` (since `A` is used for toggling anti-aliasing), so that loading new files in the folder maintains the autoplay option.

Is anyone currently working on this feature?

**Comment by Meakk** [comment]
Awesome. Please go ahead and dont hesitate to reach out on discord if you need help.  
A CLI option `--animation-autoplay` (and the config file option) would work.  
I don't think a key toggle is necessary though. We already have the key "space" to run the animation.
