### ISSUE TITLE
gnome-model-thumbnailer

### ISSUE THREAD

**Issue by alexmyczko** [f3d-app/f3d#1229]
this exists at https://gitlab.com/Kazade/gnome-model-thumbnailer/ but its previews are b/w, small. could f3d maybe get a feature to improve this?

**Comment by alexmyczko** [comment]
can f3d be used as gnome thumbnailer?

**Comment by mwestphal** [comment]
Yes, F3D supports generating thumbnails, see here: https://f3d.app/doc/user/DESKTOP_INTEGRATION.html

**Comment by mwestphal** [comment]
I will supose this is fixed then :)

**Comment by mwestphal** [comment]
It does.

**Comment by mwestphal** [comment]
https://f3d.app/doc/user/LIMITATIONS_AND_TROUBLESHOOTING.html

Some file managers (eg: Nautilus) are using sandboxing for thumbnails, which the F3D standard binary release does not support as it needs access to the Xorg server to render anything. In that case, you want to use the headless version of F3D that rely on EGL instead of Xorg, available in the [releases page](https://github.com/f3d-app/f3d/releases). If you use the portable archive, make sure to extract it somewhere the sandboxing system has access to, eg: Nautilus uses bwrap and gives it access to /usr but not to /opt.
