### ISSUE TITLE
Export to external rendering software.

### ISSUE THREAD

**Issue by nyue** [f3d-app/f3d#174]
**Is your feature request related to a problem? Please describe.**
I would like to be able to generate very high resolution rendered images suitable for posters.

**Describe the solution you'd like**
Ability to export a file from f3d for offline rendering in another software e.g. Pixar RenderMan, DNA 3Delight

**Describe alternatives you've considered**
Overload the --output option and detect the filename and if the filename ends with *.rib, call some exporter code. I am new to the code base so some of the questions I have would be (1) was such export a design consideration of f3d originally ? (2) is there an entry point where I can walk the entire scenegraph to iterate through all the geometries, textures/material, lights and cameras ?

**Contribution**
I have some familiarity on the RenderMan/3Delight side.

**Comment by mwestphal** [comment]
There is multiple layers to this, I will try to separate them.

1. Export Scene suport
In essence, what you are asking is the ability to export a scene, similar to Paraview File->ExporteScene, this may be added at some point, but it will not be added before we implement the libf3d API (#52)

2. .rib support
Once we have the support for exporting, adding support for .rib would be possible, however it would make sens to add an exporter only if we only have a reader for the format.

There is currently no importer and no exporter for .rib format in VTK. Adding both of them in VTK would be a great first step for this, especially since you already have experience in this

3. Your actual usecase
What type of rendering is missing from F3D that forces you to use an external software for that ?
Why do you use F3D at all and not the external software directly ?
I think more info about your actual usecase could help you find an alternative work around for the time being

**Comment by nyue** [comment]
@mwestphal Thank you for the explanation. I agree that any general export scene work should be done after libf3d complete.

As for RIB specifically, it is already in [implemented](https://vtk.org/doc/nightly/html/classvtkRIBExporter.html) from what I read.

Cheers

**Comment by mwestphal** [comment]
> As for RIB specifically, it is already in implemented from what I read.

Good point I missed that.

I'm still interested in your actual usecase.

**Comment by nyue** [comment]
@mwestphal I realised I can't formulate a strong use case. Initially, I was thinking of using F3D because it pulls in many scientific and engineering assets for viewing and so I can use it to perform offline render out 8k, 16k high resolution renders for posters etc but I see that F3D can already do that via OSPray. I was also pursuing external render because if I can hook up the future libf3d API to e.g. [3Delight](https://www.3delight.com/), I can leverage the rendering power of cloud computing easily.

I will think about this more in the coming months and track the libf3d API development.

Cheers

**Comment by mwestphal** [comment]
the libf3d now permits to use an external render window, in the testing directory you will find examples for glfw anf Qt. Let us know how it goes !
