### ISSUE TITLE
Choco package

### ISSUE THREAD

**Issue by pointcache** [f3d-app/f3d#221]
I know most devs don't want / have time to maintain chocolatey packages, but if you can, please.
I would love to have some high quality standard 3d viewer in my pm.

**Comment by mwestphal** [comment]
We did consider adding a chocolatey package but we have no expertise in it. Do you think you could take care of it @pointcache ?

**Comment by pointcache** [comment]
Also no expertise, but i will. Just cant promise i will maintain it long term, but ill do the initial setup.

**Comment by mwestphal** [comment]
There is a scoop package now, closing.
https://scoop.sh/#/apps?q=f3d&s=0&d=1&o=true

FYI @Meakk .

**Comment by mwestphal** [comment]
That being said, if you still want to create a Chocolatey package, you are very welcome to do so @pointcache :)

**Comment by jo-chemla** [comment]
Hey there, here are some thoughts I posted on https://github.com/evsar3/sshfs-win-manager/issues/19 to build a chocolatey package.

 - It might help to follow the [quickstart-guide](https://docs.chocolatey.org/en-us/create/create-packages-quick-start) with [automatic packages](https://docs.chocolatey.org/en-us/create/automatic-packages) - the recommended way seems to use [Chocolatey automatic updater module](https://github.com/majkinetor/au)
 - Are you using Github Actions to build the binary releases? [winget-releaser](https://github.com/marketplace/actions/winget-releaser) is a Github Action made for winget automatic package deployment during CI. A very useful [resource](https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/) explains in details how to use Github Actions YAML syntax to push choco and winget packages.
 - Otherwise, we could also try to publish a Request for Package (RFP) on [chocolatey-community/chocolatey-package-requests](https://github.com/chocolatey-community/chocolatey-package-requests) so that another maintainer would do these choco releases every time there is a github release for SSHFS-win-manager.

Hope this helps, and thanks for this great software!

**Comment by jo-chemla** [comment]
Hey again. Just submitted a PR so f3d gets listed on winget-pkgs, see PR https://github.com/microsoft/winget-pkgs/pull/172695
Once it gets listed, it should be better to setup a Github Action workflow which would push on github release the new package to winget-pkgs - see this [example post](https://github.com/try-triplex/triplex/issues/218) for two recommended ways to setup that action - usually advised to [use Winget-Releaser Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-), simpler but relies on external github action. Also another [example github action](https://github.com/th-ch/youtube-music/blob/master/.github/workflows/winget-submission.yml) workflow based on winget-releaser
