### ISSUE TITLE
Plugin architecture

### ISSUE THREAD

**Issue by Meakk** [f3d-app/f3d#374]
Allow plugin development (dynamic library loading).  
The benefits are multiple:
- Allow optional file format support in packages when there is an additional dependency
- Allow users to add their own file format support
- Make it possible to use nonpermissive third-party dependencies (or even paid)

From the user perspective, it should look like a simple `engine.loadPlugin("/path/to/plugin.so")`

**Comment by Meakk** [comment]
First version implemented by #446  

After the merge, some improvements are required:
- [ ] Install required files to create plugins outside of the source tree
- [ ] Add documentation on how to create plugins
- [ ] Add a `--plugin-list` command line option
- [ ] Add an environment variable `F3D_PLUGINS_PATH` used to look for dynamic plugins

FYI @mwestphal

**Comment by mwestphal** [comment]
- [ ] Inform packagers about the needs to distribute custom config and gather their feedbacks

**Comment by mwestphal** [comment]
About the last point, it may be required to support loading multiple config file and combine them in order to support all possible usecases, especially when external plugin will be supported adding file format F3D doesn't even know about.

it could be as simple as :

`f3d --config=config` 
-> reads `config.json` and `config.d/*.json`

`f3d --config=thumbnail`
-> reads `thumbnail.json` and `thumbnail.d/*.json`

wdyt @Meakk ?

**Comment by Meakk** [comment]
I agree, I think it's the best solution we have so far.

**Comment by Meakk** [comment]
- make official plugins buildable externally
- remove useless install SDK cmake variable

**Comment by mwestphal** [comment]
updated the list of tasks

**Comment by mwestphal** [comment]
this is complete.
