### ISSUE TITLE
Valid gltf file does not open correctly in F3D

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#457]
**Describe the bug**
A valid .gltf file is not opening correctly in F3D

[scene_pd.zip](https://github.com/f3d-app/f3d/files/9856411/scene_pd.zip)

**To Reproduce**
 1. Open the file using `f3d --dry-run scene_pd.gltf`
![a](https://user-images.githubusercontent.com/3129530/197661043-a2738ee1-3256-4485-ae0f-cf97deca2ebb.png)

**Expected behavior**
Here is how it looks in 3vviewernet:

![a](https://user-images.githubusercontent.com/3129530/197660813-0af427f0-5a8c-4d7f-8cda-b3d17b0d26c9.png)

File is valid according to glTF-Validator

**F3D Information**
Paste the content of `f3d --version`: 1.3.1

**Additional context**
Export from ParaView using the GLTF exporter, with associated point data.

**Comment by Meakk** [comment]
That's because the backside culling is enabled.  
This happens if the property `doubleSided` is not set.  
Here is the fixed gltf: [scene_pd.zip](https://github.com/f3d-app/f3d/files/10458310/scene_pd.zip)  
The issue is in the PV exporter.

![out](https://user-images.githubusercontent.com/6069752/213489011-da283cb2-e744-44ae-8496-6694ffdc9818.png)

**Comment by mwestphal** [comment]
do you mean the file is not valid ? Or at least that F3D rendering of it is as expected for this file ?

**Comment by Meakk** [comment]
It's valid, the problem is the backface culling is enabled and the faces and reversed. So, it's the expected behavior.

**Comment by mwestphal** [comment]
Got it, its a vtkGLTFExporter issue then.

**Comment by mwestphal** [comment]
https://gitlab.kitware.com/vtk/vtk/-/issues/18789
