### ISSUE TITLE
Windows F3D 2.0 generate thumbnails not run in background but foreground and steal focus of current app

### ISSUE THREAD

**Issue by GokuHiki** [f3d-app/f3d#777]
**Describe the bug**
F3D 2.0 generate thumbnails process not run in background but run in foreground and steal focus of current app.
That causes the explorer or any app is in foreground focus that lose focus and then regain focus constantly. That makes me unable to do anything when I wait for F3D generate thumbnails.

**To Reproduce**
 1. Open the folder with a lot of files obj with thumbnail preview mode.

**Expected behavior**
F3D generate thumbnails process not steal focus of other running programs.

**System Information:**
 - OS: Windows 10

**F3D Information**
F3D v2.0

Thanks and regards!

**Comment by mwestphal** [comment]
So you actually see the F3D windows appear and disappear ? What are you graphic drivers ?

**Comment by GokuHiki** [comment]
NOT 'F3D window appear and disappear'. But the current app repeats loss and regains focus!

![WindowFlicker](https://user-images.githubusercontent.com/112487208/234737916-c5f52495-50ed-4350-9b8a-758ff205213e.gif)

Because of this. When F3D generates thumbnails, you cannot do anything at all.
Also, F3D should not show loading icon at cursor when create thumbnails. It is not doing anything helpful at all. Process creating thumbnails should silent as much as possible.

**Comment by mwestphal** [comment]
I confirm that the thumbnail generation prevent the users to do something else during the generation.

In order to fix this we will need to use a more modern approach to thumbnails generation, I will open a related issue.

In any case, you also can use F3D 1.2.0 release instead of 2.0. This older release relied an another thubnails mechanism which was more efficient and do not causes this issue but could crash your explorer entirely.

https://github.com/f3d-app/f3d/releases/tag/v1.2.0

**Comment by mwestphal** [comment]
Issue opened here: #797

**Comment by mwestphal** [comment]
This actually was a 2.1.0 reggression compared to 2.0. I wish I knew that, could have been fixed much earlier.

**Comment by mwestphal** [comment]
Closed by #1031
