### ISSUE TITLE
Cycle through animations in glTF files

### ISSUE THREAD

**Issue by pfirsich** [f3d-app/f3d#902]
I searched the user documentation and looked at the help screen and searched for open issues, but could not find it, so I apologize if this feature exists.

Since glTF can have multiple animations per file, it would be good if the name of the current animation would be displayed somewhere and if there was a way (a single hotkey would be enough) to cycle through them.

**Comment by mwestphal** [comment]
You are correct, you can either select an animation or select all animations but using the command  line only. You need to restart F3D to select another animation.

That being said, adding this feature should be trivial!

**Comment by pfirsich** [comment]
I think it would also be good if there was a way to list the names of all the animations in the file with a command line switch. E.g. passing `--list-animations` would show something like this:
```
0: Idle
1: Walk
2: Die
```

**Comment by mwestphal** [comment]
--verbose already provide that

**Comment by kathleenhang** [comment]
Hi, I have been in recent communication with the F3D team on Discord, in which I mentioned my interest working on this Github issue. 

I have set up my local development environment, as well as taken a look at the VTK Users Guide and accompanying examples. I am new to learning graphics software, so I am familiarizing myself with the core concepts such as actors, mappers, renderers, pipeline, etc.

Right now, I am trying to understand which part of the F3D codebase my modifications for this issue should reside in. I'm assuming it has something to do with: library/VTKExtensions/Rendering? I have also found some related content for text such as vtkTextSource(), vtkTextMapper(), vtkTextProperty(), TextActor, etc. I'm also looking into how to extract animation data from gltf files. 

Since I am new to open source contributions, I will appreciate any additional tips!

**Comment by mwestphal** [comment]
@snoyer pointers are indeed on point.

What you need to do is add a new interaction bindings (in `f3d/library/src/interactor_impl.cxx`) that will cycle through available animations, which are recovered in the "vtkImporters" level.

It is a litle bit complicated because options like "scene.animation.index" are not great for cycling since you do not know the highest value possible.

It can be done though, you can look how cycling scalars is implemented.

@kathleenhang Ill let you investigate but feel free to ask any follow up questions.

**Comment by mwestphal** [comment]
I'll answer in detail but please open a pr directly, that will make it simpler to discuss the code :)

**Comment by mwestphal** [comment]
@pfirsich F3D nightly binary release now contains the feature!

https://github.com/f3d-app/f3d/releases/tag/nightly
